using System.Numerics;
using Content.Client.GameTicking.Managers;
using Content.Client.Message;
using Content.Shared.CartridgeLoader;
using Content.Shared.PDA;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.PDA
{
    [GenerateTypedNameReferences]
    public sealed partial class PdaMenu : PdaWindow
    {
        public const int HomeViewIndex = 0;
        public const int SettingsViewIndex = 1;
        public const int ProgramContentViewIndex = 2;

        [Dependency] private readonly IClipboardManager _clipboard = default!;
        [Dependency] private readonly IGameTiming _gameTiming = default!;
        [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
        private readonly ClientGameTicker _gameTicker;

        private string _pdaOwner = Loc.GetString("comp-pda-ui-unknown");
        private string _owner = Loc.GetString("comp-pda-ui-unknown");
        private string _jobTitle = Loc.GetString("comp-pda-ui-unassigned");
        private string _stationName = Loc.GetString("comp-pda-ui-unknown");
        private string _alertLevel = Loc.GetString("comp-pda-ui-unknown");
        private string _instructions = Loc.GetString("comp-pda-ui-unknown");

        private int _currentView;

        public event Action? OnProgramDeactivated;

        public PdaMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();

            // Add border to ProgramBar
            ProgramBarBorder.PanelOverride = new StyleBoxFlat
            {
                BorderColor = Color.FromHex("#5a5a5a"),
                BorderThickness = new Thickness(1),
                BackgroundColor = Color.FromHex("#1a1a1e"),
            };

            HomeButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/home.png"));
            FlashLightToggleButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/light.png"));
            EjectPenButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pencil.png"));
            EjectIdButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/eject.png"));
            EjectPaiButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pai.png"));

            HomeButton.OnPressed += _ => ToHomeScreen();
            SettingsButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                SettingsButton.IsCurrent = true;

                // Switch to settings view first, then deactivate program
                ChangeView(SettingsViewIndex);
                DeactivateActiveProgram();
            };
            PdaOwnerButton.OnPressed += _ =>
            {
                _clipboard.SetText(_pdaOwner);
            };
            IdInfoButton.OnPressed += _ =>
            {
                _clipboard.SetText(_owner + ", " + _jobTitle);
            };
            StationNameButton.OnPressed += _ =>
            {
                _clipboard.SetText(_stationName);
            };
            StationAlertLevelButton.OnPressed += _ =>
            {
                _clipboard.SetText(_alertLevel);
            };
            StationTimeButton.OnPressed += _ =>
            {
                var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
                _clipboard.SetText(stationTime.ToString("hh\\:mm\\:ss"));
            };
            StationAlertLevelInstructionsButton.OnPressed += _ =>
            {
                _clipboard.SetText(_instructions);
            };




            HideAllViews();
            ToHomeScreen();
        }

        public void UpdateState(PdaUpdateState state)
        {
            FlashLightToggleButton.IsActive = state.FlashlightEnabled;

            if (state.PdaOwnerInfo.ActualOwnerName != null)
            {
                _pdaOwner = state.PdaOwnerInfo.ActualOwnerName;
                PdaOwnerLabel.SetMarkup(Loc.GetString("comp-pda-ui-owner",
                    ("actualOwnerName", _pdaOwner)));
                PdaOwnerLabel.Visible = true;
            }
            else
            {
                PdaOwnerLabel.Visible = false;
            }


            if (state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null)
            {
                _owner = state.PdaOwnerInfo.IdOwner ?? Loc.GetString("comp-pda-ui-unknown");
                _jobTitle = state.PdaOwnerInfo.JobTitle ?? Loc.GetString("comp-pda-ui-unassigned");
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui",
                    ("owner", _owner),
                    ("jobTitle", _jobTitle)));
            }
            else
            {
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui-blank"));
            }

            _stationName = state.StationName ?? Loc.GetString("comp-pda-ui-unknown");
            StationNameLabel.SetMarkup(Loc.GetString("comp-pda-ui-station",
                ("station", _stationName)));


            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);

            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time-stalker", // stalker-en-changes - PDA UI
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));

            var alertLevel = state.PdaOwnerInfo.StationAlertLevel;
            var alertColor = state.PdaOwnerInfo.StationAlertColor;
            var alertLevelKey = alertLevel != null ? $"alert-level-{alertLevel}" : "alert-level-unknown";
            _alertLevel = Loc.GetString(alertLevelKey);

            StationAlertLevelLabel.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level",
                ("color", alertColor),
                ("level", _alertLevel)
            ));
            _instructions = Loc.GetString($"{alertLevelKey}-instructions");
            StationAlertLevelInstructions.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level-instructions",
                ("instructions", _instructions))
            );

            AddressLabel.Text = state.Address?.ToUpper() ?? " - ";

            EjectIdButton.IsActive = state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null;
            EjectPenButton.IsActive = state.HasPen;
            EjectPaiButton.IsActive = state.HasPai;
            ActivateMusicButton.Visible = state.CanPlayMusic;
            ShowUplinkButton.Visible = state.HasUplink;
            LockUplinkButton.Visible = state.HasUplink;

            // stalker-changes-start - Update silent mode button text based on state
            SilentModeButton.Text = state.SilentModeEnabled
                ? Loc.GetString("comp-pda-ui-silent-mode-button-on")
                : Loc.GetString("comp-pda-ui-silent-mode-button-off");
            // stalker-changes-end

            // stalker-en-changes - PDA layout changes
            StalkerWeekLabel.SetMarkup(Loc.GetString("comp-pda-week-label", ("week", _gameTicker.RoundId)));
            // stalker-en-changes-end
        }

        private EntityUid? _activeProgram;

        public void UpdateAvailablePrograms(List<(EntityUid, CartridgeComponent)> programs, Action<EntityUid> onActivate, Action<EntityUid> onInstall, Action<EntityUid> onUninstall)
        {
            ProgramBarContent.RemoveAllChildren();

            if (programs.Count == 0)
            {
                ProgramBarContent.AddChild(new Label()
                {
                    Text = Loc.GetString("comp-pda-io-no-programs-available"),
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    VerticalExpand = true
                });

                return;
            }

            foreach (var (uid, component) in programs)
            {
                var item = new PdaProgramItem();
                item.ProgramTitle = Loc.GetString(component.ProgramName);

                if (component.Icon is not null)
                    item.Icon.SetFromSpriteSpecifier(component.Icon);

                // Highlight if this is the active program
                if (_activeProgram == uid)
                    item.BackgroundColor = Color.FromHex("#316dca");

                item.OnPressed += _ =>
                {
                    if (_activeProgram.HasValue && _activeProgram.Value != uid)
                        OnProgramDeactivated?.Invoke();
                    _activeProgram = uid;
                    onActivate(uid);
                };

                switch (component.InstallationStatus)
                {
                    case InstallationStatus.Cartridge:
                        item.InstallButton.Visible = true;
                        item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-install-button");
                        item.InstallButton.OnPressed += _ => onInstall(uid);
                        break;
                    case InstallationStatus.Installed:
                        item.InstallButton.Visible = true;
                        item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-uninstall-button");
                        item.InstallButton.OnPressed += _ => onUninstall(uid);
                        break;
                }

                item.NotificationDot.Visible = component.HasNotification;
                if (component.HasNotification)
                {
                    item.NotificationDot.PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = Color.FromHex("#CC4444"),
                    };
                }

                ProgramBarContent.AddChild(item);
            }
        }

        /// <summary>
        /// Changes the current view to the home screen and deactivates any active program
        /// </summary>
        public void ToHomeScreen()
        {
            HomeButton.IsCurrent = true;
            SettingsButton.IsCurrent = false;

            DeactivateActiveProgram();
            ChangeView(HomeViewIndex);
        }

        /// <summary>
        /// Deactivates the currently active program and triggers the deactivation event
        /// </summary>
        public void DeactivateActiveProgram()
        {
            if (_activeProgram.HasValue)
            {
                _activeProgram = null;
                OnProgramDeactivated?.Invoke();
                // Refresh program bar to remove highlight
                // Note: The caller should call UpdateAvailablePrograms again to refresh visuals
            }
        }

        /// <summary>
        /// Changes the current view to the program content view
        /// </summary>
        public void ToProgramView()
        {
            HomeButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;

            ChangeView(ProgramContentViewIndex);
        }

        /// <summary>
        /// Gets the currently active view number
        /// </summary>
        public int GetCurrentView() => _currentView;


        /// <summary>
        /// Changes the current view to the given view number
        /// </summary>
        public void ChangeView(int view)
        {
            // Use named references instead of relying on child order
            var views = new Control[] { HomeView, SettingsView, ProgramView };

            if (views.Length <= view || view < 0)
                return;

            for (var i = 0; i < views.Length; i++)
            {
                views[i].Visible = (i == view);
            }

            _currentView = view;
        }

        private void HideAllViews()
        {
            HomeView.Visible = false;
            SettingsView.Visible = false;
            ProgramView.Visible = false;
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);

            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
            
            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time-stalker", // Stalker-en-changes - PDA UI
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));
        }
    }
}
