using System.Numerics;
using Content.Client._Stalker_EN.FactionRelations;
using Content.Shared._Stalker_EN.Leaderboard;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.Leaderboard;

[GenerateTypedNameReferences]
public sealed partial class STLeaderboardUiFragment : BoxContainer
{
    private SpriteSystem? _spriteSystem;
    private IGameTiming? _timing;

    private SpriteSystem SpriteSystem => _spriteSystem ??= IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

    public Action? OnRefresh;

    private TimeSpan _nextRefreshTime;
    private static readonly TimeSpan RefreshCooldown = TimeSpan.FromSeconds(30);

    public STLeaderboardUiFragment()
    {
        RobustXamlLoader.Load(this);
        _timing = IoCManager.Resolve<IGameTiming>();
        _nextRefreshTime = _timing.CurTime;

        RefreshButton.OnPressed += _ =>
        {
            if (_timing!.CurTime < _nextRefreshTime)
                return;

            _nextRefreshTime = _timing.CurTime + RefreshCooldown;
            RefreshButton.Disabled = true;
            RefreshButton.Text = Loc.GetString("st-leaderboard-refresh-cooldown");

            Timer.Spawn(RefreshCooldown, () =>
            {
                if (RefreshButton != null)
                {
                    RefreshButton.Disabled = false;
                    RefreshButton.Text = Loc.GetString("st-leaderboard-refresh");
                }
            });

            OnRefresh?.Invoke();
        };
    }

    public void UpdateState(List<STLeaderboardEntry> entries)
    {
        EntriesList.RemoveAllChildren();

        STLeaderboardEntry? myStats = null;
        foreach (var entry in entries)
        {
            if (entry.IsMe)
            {
                myStats = entry;
                break;
            }
        }

        var killsCount = myStats?.MutantsKilled ?? 0;
        var artsCount = myStats?.ArtifactsFound ?? 0;

        var killsMsg = new FormattedMessage();
        killsMsg.AddMarkupOrThrow($"[b]{Loc.GetString("st-leaderboard-stats-kills-label")}[/b] {killsCount}");
        StatsKills.SetMessage(killsMsg);

        var artsMsg = new FormattedMessage();
        artsMsg.AddMarkupOrThrow($"[b]{Loc.GetString("st-leaderboard-stats-arts-label")}[/b] {artsCount}");
        StatsArts.SetMessage(artsMsg);

        STLeaderboardEntry? myEntry = null;
        int myPosition = -1;
        int position = 1;

        foreach (var entry in entries)
        {
            var row = _makeEntry(position, entry);
            EntriesList.AddChild(row);

            if (entry.IsMe)
            {
                myEntry = entry;
                myPosition = position;
            }

            position++;
        }

        // Show pinned entry below the scroll area — always visible, same position as in list
        PinnedContainer.Visible = myEntry.HasValue;
        PinnedEntry.RemoveAllChildren();
        if (myEntry.HasValue && myPosition > 0)
        {
            var pinnedRow = _makeEntry(myPosition, myEntry.Value);
            PinnedEntry.AddChild(pinnedRow);
        }
    }

    private Control _makeEntry(int position, STLeaderboardEntry entry)
    {
        var container = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Margin = new Thickness(8, 4),
            HorizontalExpand = true,
        };

        var iconPanel = new PanelContainer
        {
            MinSize = new Vector2(64, 64),
            Margin = new Thickness(0, 0, 8, 0),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#222222"),
            },
        };

        iconPanel.AddChild(_getBandIconTexture(entry.BandName));
        container.AddChild(iconPanel);

        var infoBlock = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            VerticalExpand = true,
            HorizontalExpand = true,
        };

        var nameLine = new RichTextLabel { HorizontalExpand = true, Margin = new Thickness(0, 0, 0, 2) };
        var nameMsg = new FormattedMessage();
        nameMsg.AddMarkupOrThrow($"[b]{position}. {FormattedMessage.EscapeText(entry.CharacterName)}[/b]");
        nameLine.SetMessage(nameMsg);
        infoBlock.AddChild(nameLine);

        var factionDisplay = entry.BandName ?? Loc.GetString("st-leaderboard-nodata");
        var factionColor = _getRelationColor(entry.BandRelation);
        var factionLine = new RichTextLabel { HorizontalExpand = true, Margin = new Thickness(0, 0, 0, 2) };
        var factionMsg = new FormattedMessage();
        factionMsg.PushColor(factionColor);
        factionMsg.AddText($"{Loc.GetString("st-leaderboard-faction-label")} {factionDisplay}");
        factionMsg.Pop();
        factionLine.SetMessage(factionMsg);
        infoBlock.AddChild(factionLine);

        var rankDisplay = entry.RankName != null ? Loc.GetString(entry.RankName) : Loc.GetString("st-leaderboard-nodata");
        var rankLine = new RichTextLabel { HorizontalExpand = true };
        var rankMsg = new FormattedMessage();
        rankMsg.AddText($"{Loc.GetString("st-leaderboard-rank-label")} {rankDisplay}");
        rankLine.SetMessage(rankMsg);
        infoBlock.AddChild(rankLine);

        container.AddChild(infoBlock);
        return container;
    }

    private static Color _getRelationColor(STLeaderboardFactionRelation relation) => relation switch
    {
        STLeaderboardFactionRelation.Same => Color.FromHex("#33CC33"),
        STLeaderboardFactionRelation.Alliance => Color.FromHex("#33CC33"),
        STLeaderboardFactionRelation.Neutral => Color.FromHex("#FFD700"),
        STLeaderboardFactionRelation.Hostile => Color.FromHex("#FF8800"),
        STLeaderboardFactionRelation.War => Color.FromHex("#FF4444"),
        _ => Color.FromHex("#CCCCCC"),
    };

    private static readonly ResPath LeaderboardRsiPath = new("/Textures/_Stalker_EN/Interface/Cartridges/leaderboard.rsi");

    private Control _getBandIconTexture(string? bandName)
    {
        SpriteSpecifier specifier;

        if (string.IsNullOrEmpty(bandName) || bandName == "—")
        {
            specifier = new SpriteSpecifier.Rsi(LeaderboardRsiPath, "nodata");
        }
        else
        {
            var patchKey = bandName switch
            {
                "Stalker" or "Loner" => "Loners",
                "Freedom" => "Freedom",
                "Bandit" => "Bandits",
                "Dolg" or "Duty" => "Duty",
                "Sci" or "Scientist" or "Ecologist" => "Ecologist",
                "Merc" or "Mercenary" => "Mercenaries",
                "Military" or "Army" => "Military",
                "Monolith" => "Monolith",
                "ClearSky" or "CN" => "ClearSky",
                "Renegade" => "Renegades",
                "Rookie" => "Rookies",
                "Journalist" => "Journalists",
                "UN" => "UN",
                "Militia" => "Neutrals",
                _ => bandName,
            };

            specifier = STFactionPatchIcons.PatchStates.TryGetValue(patchKey, out var patch)
                ? new SpriteSpecifier.Rsi(patch.Rsi, patch.State)
                : new SpriteSpecifier.Rsi(LeaderboardRsiPath, "nodata");
        }

        var texture = SpriteSystem.Frame0(specifier);
        return new TextureRect
        {
            Texture = texture,
            TextureScale = new Vector2(2f, 2f),
            Stretch = TextureRect.StretchMode.KeepCentered,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };
    }
}
